In [ ]:
#!pip install pandas
#!pip install openpyxl
#!pip install plotly
#!pip install nbformat

# Cargar datos desde un archivo de excel

In [4]:
import pandas as pd
import plotly.express as px

In [5]:
pd.read_excel("ventas.xlsx")

,region,fecha,tienda,Ciudad,País,tamaño,local_consumo,precio,forma_pago
0,PED1994,2022-01-01,Tienda 4,Guadalajara,México,300ml,Consumo en tienda,5,Efectivo
1,PED2246,2022-01-01,Tienda 6,Santiago de Chile,Chile,500ml,Consumo en tienda,11,Débito
2,PED3876,2022-01-01,Tienda 3,Bogotá,Colombia,300ml,Delivery,7,Crédito
3,PED4352,2022-01-01,Tienda 1,Buenos Aires,Argentina,1000ml,Consumo en tienda,7,Débito
4,PED8633,2022-01-01,Tienda 5,Ciudad de México,México,200ml,Delivery,9,Crédito
...,...,...,...,...,...,...,...,...,...
69995,PED67084,2024-12-31,Tienda 6,Santiago de Chile,Chile,500ml,Consumo en tienda,11,Crédito
69996,PED67857,2024-12-31,Tienda 3,Bogotá,Colombia,200ml,Consumo en tienda,7,Nequi
69997,PED69171,2024-12-31,Tienda 4,Guadalajara,México,500ml,Consumo en tienda,5,Efectivo
69998,PED69229,2024-12-31,Tienda 4,Guadalajara,México,300ml,Consumo en tienda,9,Nequi
69999,PED69356,2024-12-31,Tienda 1,Buenos Aires,Argentina,300ml,Delivery,9,Nequi

## Primeros datos de la serie de datos

In [6]:
data = pd.read_excel("ventas.xlsx")

data.head()

,region,fecha,tienda,Ciudad,País,tamaño,local_consumo,precio,forma_pago
0,PED1994,2022-01-01,Tienda 4,Guadalajara,México,300ml,Consumo en tienda,5,Efectivo
1,PED2246,2022-01-01,Tienda 6,Santiago de Chile,Chile,500ml,Consumo en tienda,11,Débito
2,PED3876,2022-01-01,Tienda 3,Bogotá,Colombia,300ml,Delivery,7,Crédito
3,PED4352,2022-01-01,Tienda 1,Buenos Aires,Argentina,1000ml,Consumo en tienda,7,Débito
4,PED8633,2022-01-01,Tienda 5,Ciudad de México,México,200ml,Delivery,9,Crédito

## Ultimos datos de la serie de datos

In [7]:
data.tail()

,region,fecha,tienda,Ciudad,País,tamaño,local_consumo,precio,forma_pago
69995,PED67084,2024-12-31,Tienda 6,Santiago de Chile,Chile,500ml,Consumo en tienda,11,Crédito
69996,PED67857,2024-12-31,Tienda 3,Bogotá,Colombia,200ml,Consumo en tienda,7,Nequi
69997,PED69171,2024-12-31,Tienda 4,Guadalajara,México,500ml,Consumo en tienda,5,Efectivo
69998,PED69229,2024-12-31,Tienda 4,Guadalajara,México,300ml,Consumo en tienda,9,Nequi
69999,PED69356,2024-12-31,Tienda 1,Buenos Aires,Argentina,300ml,Delivery,9,Nequi

## Traemos solo los datos de una columna

In [ ]:
data.Ciudad

<bound method Series.diff of 0              Guadalajara
1        Santiago de Chile
2                   Bogotá
3             Buenos Aires
4         Ciudad de México
               ...
69995    Santiago de Chile
69996               Bogotá
69997          Guadalajara
69998          Guadalajara
69999         Buenos Aires
Name: Ciudad, Length: 70000, dtype: str>

In [10]:
data["tienda"]

0        Tienda 4
1        Tienda 6
2        Tienda 3
3        Tienda 1
4        Tienda 5
           ...
69995    Tienda 6
69996    Tienda 3
69997    Tienda 4
69998    Tienda 4
69999    Tienda 1
Name: tienda, Length: 70000, dtype: str

In [12]:
data[["tienda", "Ciudad"]]

         tienda             Ciudad
0      Tienda 4        Guadalajara
1      Tienda 6  Santiago de Chile
2      Tienda 3             Bogotá
3      Tienda 1       Buenos Aires
4      Tienda 5   Ciudad de México
...         ...                ...
69995  Tienda 6  Santiago de Chile
69996  Tienda 3             Bogotá
69997  Tienda 4        Guadalajara
69998  Tienda 4        Guadalajara
69999  Tienda 1       Buenos Aires

[70000 rows x 2 columns]

# Estadisticas

In [13]:
data.describe()

                            fecha        precio
count                       70000  70000.000000
mean   2023-10-02 07:40:07.268571      8.355200
min           2022-01-01 00:00:00      5.000000
25%           2023-01-01 00:00:00      7.000000
50%           2024-01-02 00:00:00      7.000000
75%           2024-07-02 00:00:00     11.000000
max           2024-12-31 00:00:00     13.000000
std                           NaN      2.653061

# Analisis de datos

In [15]:
data["tienda"].unique()

<StringArray>
['Tienda 4', 'Tienda 6', 'Tienda 3', 'Tienda 1', 'Tienda 5', 'Tienda 2']
Length: 6, dtype: str

In [16]:
data["tienda"].value_counts()

tienda
Tienda 4    13483
Tienda 6    13075
Tienda 1    12344
Tienda 5    12177
Tienda 3    10603
Tienda 2     8318
Name: count, dtype: int64

In [18]:
data["Ciudad"].value_counts()

Ciudad
Guadalajara          13483
Santiago de Chile    13075
Buenos Aires         12344
Ciudad de México     12177
Bogotá               10603
Medellín              8318
Name: count, dtype: int64

In [20]:
data["forma_pago"].value_counts()

forma_pago
Crédito     26063
Débito      20427
Efectivo    14709
Nequi        8801
Name: count, dtype: int64

# Agrupar datos

In [21]:
data.groupby("tienda")["precio"].sum()

tienda
Tienda 1    103162
Tienda 2     69592
Tienda 3     88357
Tienda 4    112379
Tienda 5    102189
Tienda 6    109185
Name: precio, dtype: int64

# Colocar en tabla

In [23]:
data.groupby("forma_pago")["precio"].sum().to_frame()

            precio
forma_pago
Crédito     217563
Débito      170765
Efectivo    123239
Nequi        73297

In [25]:
data.groupby(["tienda","forma_pago"])["precio"].sum().to_frame()

                     precio
tienda   forma_pago
Tienda 1 Crédito      38464
         Débito       29859
         Efectivo     21702
         Nequi        13137
Tienda 2 Crédito      25702
         Débito       20756
         Efectivo     14785
         Nequi         8349
Tienda 3 Crédito      32343
         Débito       25581
         Efectivo     18188
         Nequi        12245
Tienda 4 Crédito      42047
         Débito       32245
         Efectivo     24124
         Nequi        13963
Tienda 5 Crédito      38354
         Débito       30171
         Efectivo     21381
         Nequi        12283
Tienda 6 Crédito      40653
         Débito       32153
         Efectivo     23059
         Nequi        13320

# Exportar a un Excel

In [26]:
datos_agrupados = data.groupby(["tienda","forma_pago"])["precio"].sum().to_frame()
datos_agrupados.to_excel("facturacion.xlsx")

# Graficos

In [ ]:
px.histogram(data, x="tienda")

In [29]:
px.histogram(data, 
             x = "tienda",
             text_auto = True,
             title = "Facturación",
             color = "forma_pago")

In [31]:
grafico = px.histogram(data, 
                       x = "tienda",
                       text_auto = True,
                       title = "Facturación",
                       color = "forma_pago")

#grafico.show()
grafico.write_html("facturacion.html")

In [33]:
columnas = ['tienda', 'ciudad', 'pais', 'local_consumo']

for columna in columnas:
    fig = px.histogram(data, 
                       x = "tienda",
                       text_auto = True,
                       title = "Facturación",
                       color = "forma_pago")
    fig.write_html(f"facturación por {columna}.html")
    fig.show()

# Gráfica interactiva por mes

In [40]:
# Generamos la columna anio_mes
data['fecha'] = pd.to_datetime(data['fecha'])
data['anio_mes'] = data['fecha'].dt.to_period('M')



# Agrupamos los datos
#agrupado = data.groupby(['tienda', 'anio_mes']).precio.sum().to_frame()

# Reset de los indices
#agrupado.reset_index(inplace=True)

# Se puede agrupar sin el frame
agrupado = (
    data
    .groupby(['tienda', 'anio_mes'], as_index=False)['precio']
    .sum()
)

#ordenamos los periodos y las tiendas
agrupado = agrupado.sort_values('anio_mes')
orden_tiendas = sorted(agrupado['tienda'].unique())


# Creando una columna con el valor acumulado
agrupado['acumulado'] = agrupado.groupby('tienda').precio.cumsum()

#Generar gráfico
graf = px.bar(agrupado,
              x = 'acumulado',
              y = 'tienda',
              color = 'tienda',
              text_auto = True,
              range_x = [0,160000],
              animation_frame = 'anio_mes',
              category_orders = {'tienda': orden_tiendas}
              )
graf.show()

# Ranking de ventras por mes

In [43]:
import pandas as pd
import plotly.express as px

# 1) Asegurar fecha + anio_mes
data['fecha'] = pd.to_datetime(data['fecha'])
data['anio_mes'] = data['fecha'].dt.to_period('M').astype(str)

# 2) Ventas del mes por tienda
mensual = (
    data.groupby(['tienda', 'anio_mes'], as_index=False)['precio']
        .sum()
        .sort_values('anio_mes')
)

# 3) Gráfica ranking (bar race)
graf = px.bar(
    mensual,
    x='precio',
    y='tienda',
    color='tienda',
    text='precio',                 # usaremos formato custom
    animation_frame='anio_mes',
    range_x=[0, mensual['precio'].max() * 1.15],
    labels={
        'anio': 'Año',
        'precio': 'Ventas (USD)',
        'tienda': 'Tiendas'
    }
)

# 4) Formato: USD + separador de miles (ej: $12,345)
graf.update_traces(texttemplate='$%{x:,.0f}', textposition='outside')

# 5) Eje X con separador de miles también
graf.update_xaxes(tickformat='$,.0f')

# 6) Ranking dinámico: orden por valor del frame
# (si el #1 te queda abajo, cambia a 'total descending')
graf.update_layout(yaxis={'categoryorder': 'total ascending'})

graf.show()

# Ranking por año con pausas

In [ ]:
import pandas as pd
import plotly.express as px

# 1) Tomar de la fecha el anio
data['anio'] = pd.to_datetime(data['fecha']).dt.year

# 2) Ventas anuales por tienda
anual = (
    data.groupby(['tienda', 'anio'], as_index=False)['precio']
        .sum()
)

# 3) Gráfica ranking anual
graf = px.bar(
    anual,
    x='precio',
    y='tienda',
    color='tienda',
    text='precio',
    animation_frame='anio',
    range_x=[0, anual['precio'].max() * 1.15],
    labels={
        'anio': 'Año',
        'precio': 'Ventas (USD)',
        'tienda': 'Tienda'
    }
)

# 4) Formato: USD + separador de miles (ej: $12,345)
graf.update_traces(texttemplate='$%{x:,.0f}', textposition='outside')

# 5) Eje X con separador de miles también
graf.update_xaxes(tickformat='$,.0f')

# 6) Ranking dinámico: orden por valor del frame
graf.update_layout(yaxis={'categoryorder': 'total ascending'})

# Pausas anuales
graf.update_layout(
    updatemenus=[{
        "buttons": [{
            "args": [
                None,
                {
                    "frame": {"duration": 5000, "redraw": True},
                    "transition": {"duration": 500},
                    "fromcurrent": True
                }
            ],
            "method": "animate"
        }]
    }]
)

#título dinámico
graf.update_layout(
    title={
        'text': "Ventas por Tienda",
        'x': 0.5,
        'xanchor': 'center'
    }
)

for frame in graf.frames:
    frame.layout = {
        "title_text": f"Ventas por Tienda — Año {frame.name}"
    }

graf.show()